"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { usePathname } from "next/navigation";
import AppProvider from "./AppProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Remove this from here since we're using "use client"
// export const metadata: Metadata = {
//   title: "AcademiaHub",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // List of paths where navbar should be hidden (auth pages)
  const authPages = [
    "/login",
    "/signup",
    "/reset-password",
    "/profile-setup",
    "/verification",
    "/user-registration",
  ];

  const userPage = [
    "/dashboard",
    "/analytics",
    "/downloads",
    "/uploads",
    "/saved",
    "/inbox",
    "/profile",
    "/settings",
  ];
  const isAuthPage = authPages.includes(pathname);
  const isUserPage = userPage.includes(pathname);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <AppProvider>
          {!isAuthPage && !isUserPage && <Navbar />}
          {children}
          <Toaster position="top-right" reverseOrder={false} />
           {!isAuthPage && !isUserPage && <Footer />}
        </AppProvider>
      </body>
    </html>
  );
}
